import React from 'react'

const part = [
    'web Design',
    'Back end Dev',
    'Front end Dev',
    'Android Dev',
    'web Design',
    'Back end Dev',
    'Front end Dev',
    'Android Dev',
    'web Design',
    'Back end Dev',
    'Front end Dev',
    'Android Dev',
    'web Design',
    'Back end Dev',
    'Front end Dev',
    'Android Dev',
    'web Design',
    'Back end Dev',
    'Front end Dev',
    'Android Dev',
    'web Design',
    'Back end Dev',
    'Front end Dev',
    'Android Dev',
    'web Design',
    'Back end Dev',
    'Front end Dev',
    'Android Dev',
    'web Design',
    'Back end Dev',
    'Front end Dev',
    'Android Dev',
    'web Design',
    'Back end Dev',
    'Front end Dev',
    'Android Dev',
    'web Design',
    'Back end Dev',
    'Front end Dev',
    'Android Dev',
    'web Design',
    'Back end Dev',
    'Front end Dev',
    'Android Dev',
    'web Design',
    'Back end Dev',
    'Front end Dev',
    'Android Dev',
    'web Design',
    'Back end Dev',
    'Front end Dev',
    'Android Dev',
    'web Design',
    'Back end Dev',
    'Front end Dev',
    'Android Dev',
    'web Design',
    'Back end Dev',
    'Front end Dev',
    'Android Dev',
    'web Design',
    'Back end Dev',
    'Front end Dev',
    'Android Dev',
    'web Design',
    'Back end Dev',
    'Front end Dev',
    'Android Dev',
    'web Design',
    'Back end Dev',
    'Front end Dev',
    'Android Dev',
    'web Design',
    'Back end Dev',
    'Front end Dev',
    'Android Dev',
    'web Design',
    'Back end Dev',
    'Front end Dev',
    'Android Dev',
    'web Design',
    'Back end Dev',
    'Front end Dev',
    'Android Dev',
    'web Design',
    'Back end Dev',
    'Front end Dev',
    'Android Dev',
    'web Design',
    'Back end Dev',
    'Front end Dev',
    'Android Dev',
    'web Design',
    'Back end Dev',
    'Front end Dev',
    'Android Dev',
    'web Design',
    'Back end Dev',
    'Front end Dev',
    'Android Dev',
    'web Design',
    'Back end Dev',
    'Front end Dev',
    'Android Dev',
    'web Design',
    'Back end Dev',
    'Front end Dev',
    'Android Dev',
    'web Design',
    'Back end Dev',
    'Front end Dev',
    'Android Dev',
    'web Design',
    'Back end Dev',
    'Front end Dev',
    'Android Dev',
    'web Design',
    'Back end Dev',
    'Front end Dev',
    'Android Dev',
    'web Design',
    'Back end Dev',
    'Front end Dev',
    'Android Dev',
    'web Design',
    'Back end Dev',
    'Front end Dev',
    'Android Dev',
    'web Design',
    'Back end Dev',
    'Front end Dev',
    'Android Dev',
    'web Design',
    'Back end Dev',
    'Front end Dev',
    'Android Dev',
    'web Design',
    'Back end Dev',
    'Front end Dev',
    'Android Dev',
    'web Design',
    'Back end Dev',
    'Front end Dev',
    'Android Dev',
    'web Design',
    'Back end Dev',
    'Front end Dev',
    'Android Dev',
    'web Design',
    'Back end Dev',
    'Front end Dev',
    'Android Dev',
    'web Design',
    'Back end Dev',
    'Front end Dev',
    'Android Dev',
    'web Design',
    'Back end Dev',
    'Front end Dev',
    'Android Dev',
    'web Design',
    'Back end Dev',
    'Front end Dev',
    'Android Dev',
    'web Design',
    'Back end Dev',
    'Front end Dev',
    'Android Dev',
  ]

  export default part
