import './globals.css'
import { Inter } from 'next/font/google'
import './style.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Salman Alfarizqi',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className='!scroll-smooth'>
      <body className="bg-white bg-no-repeat">{children}</body>
    </html>
  )
}
